//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Script/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""ControlsMap"",
            ""id"": ""01c2d724-a101-4b0f-b96d-101c8237453a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2b07cf4c-0661-43c1-be4f-4d77e423c1af"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectDanceMove"",
                    ""type"": ""Button"",
                    ""id"": ""f0ff73a2-6529-4ac0-899d-fb0abca40a03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnLight"",
                    ""type"": ""Button"",
                    ""id"": ""e9cd74c1-51a8-4570-b591-10e5562ef78a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""3e7ba516-b860-492d-bae0-e5b4d3823a99"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""10ba17aa-7ab1-45d4-b987-2b3eacdb6eb4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""82e3eae2-0aad-4dce-9743-602333f8647b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e33c2262-5b92-42ef-88d6-3b9d6cb9f514"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fa3f840f-a1f2-4aac-b9e1-3d050208dab5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6c565cac-da80-4663-b6a8-d4b779738cac"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0474ca67-a05f-4a32-b53d-be12e568319f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a806d9e8-8597-4de0-bef2-a14e45bb4159"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3082e017-6823-4eb3-a6bd-d7c932b462cb"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=4)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83698c6e-e547-48c3-b3e2-8adc343be9ef"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=5)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1127666b-6bff-4da6-8b8b-122a7baecfd4"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=6)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab0ddb5d-7a55-4a93-acc7-2215a6b35bbc"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=7)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4d69500-9a53-4fb0-85ad-585e6aa47451"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=8)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1eef3833-7052-4225-811b-e0cc677b231e"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=9)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21f4cd3e-073f-43f4-bb6b-ab3e6f9b3091"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=10)"",
                    ""groups"": """",
                    ""action"": ""SelectDanceMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e201b80-e7bd-40fe-a8f7-84dcf9982882"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnLight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ControlsMap
        m_ControlsMap = asset.FindActionMap("ControlsMap", throwIfNotFound: true);
        m_ControlsMap_Move = m_ControlsMap.FindAction("Move", throwIfNotFound: true);
        m_ControlsMap_SelectDanceMove = m_ControlsMap.FindAction("SelectDanceMove", throwIfNotFound: true);
        m_ControlsMap_SpawnLight = m_ControlsMap.FindAction("SpawnLight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlsMap
    private readonly InputActionMap m_ControlsMap;
    private IControlsMapActions m_ControlsMapActionsCallbackInterface;
    private readonly InputAction m_ControlsMap_Move;
    private readonly InputAction m_ControlsMap_SelectDanceMove;
    private readonly InputAction m_ControlsMap_SpawnLight;
    public struct ControlsMapActions
    {
        private @Controls m_Wrapper;
        public ControlsMapActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ControlsMap_Move;
        public InputAction @SelectDanceMove => m_Wrapper.m_ControlsMap_SelectDanceMove;
        public InputAction @SpawnLight => m_Wrapper.m_ControlsMap_SpawnLight;
        public InputActionMap Get() { return m_Wrapper.m_ControlsMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsMapActions set) { return set.Get(); }
        public void SetCallbacks(IControlsMapActions instance)
        {
            if (m_Wrapper.m_ControlsMapActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnMove;
                @SelectDanceMove.started -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnSelectDanceMove;
                @SelectDanceMove.performed -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnSelectDanceMove;
                @SelectDanceMove.canceled -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnSelectDanceMove;
                @SpawnLight.started -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnSpawnLight;
                @SpawnLight.performed -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnSpawnLight;
                @SpawnLight.canceled -= m_Wrapper.m_ControlsMapActionsCallbackInterface.OnSpawnLight;
            }
            m_Wrapper.m_ControlsMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @SelectDanceMove.started += instance.OnSelectDanceMove;
                @SelectDanceMove.performed += instance.OnSelectDanceMove;
                @SelectDanceMove.canceled += instance.OnSelectDanceMove;
                @SpawnLight.started += instance.OnSpawnLight;
                @SpawnLight.performed += instance.OnSpawnLight;
                @SpawnLight.canceled += instance.OnSpawnLight;
            }
        }
    }
    public ControlsMapActions @ControlsMap => new ControlsMapActions(this);
    public interface IControlsMapActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSelectDanceMove(InputAction.CallbackContext context);
        void OnSpawnLight(InputAction.CallbackContext context);
    }
}
